baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Joseph Madden'
theme = 'myTheme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'CV / Contact'
pageRef = '/cv'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40
